NumPy (Numerical Python) is a powerful Python library for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

In [2]:
import numpy

In [3]:
import numpy as np

In [4]:
arr1 = np.array([1,2,3,4,5])

In [5]:
arr1

array([1, 2, 3, 4, 5])

In [6]:
arr2 = np.array([[1,2,3], [4,5,6]])

In [7]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr3 = np.array([
    [[1,2], [3,4]],
    [[5,6],[7,8]]
    ])

In [9]:
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [10]:
#metrix

In [11]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
zero_matrix = list(map(lambda _: [0] * 3, range(3)))

In [13]:
zero_matrix

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]

In [14]:
zero_matrix = []
for _ in range(3):
    zero_matrix.append([0] * 3)

print(zero_matrix)


[[0, 0, 0], [0, 0, 0], [0, 0, 0]]


In [15]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [16]:
np.full((3,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#range

In [18]:
np.arange(1,10,2)   # 1 to 10 is the range, and 2 is stepsize

array([1, 3, 5, 7, 9])

In [19]:
np.arange(1.0,5.0,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [20]:
np.linspace(1,10,7)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [21]:
np.linspace(1,30,20)

array([ 1.        ,  2.52631579,  4.05263158,  5.57894737,  7.10526316,
        8.63157895, 10.15789474, 11.68421053, 13.21052632, 14.73684211,
       16.26315789, 17.78947368, 19.31578947, 20.84210526, 22.36842105,
       23.89473684, 25.42105263, 26.94736842, 28.47368421, 30.        ])

#random

In [ ]:
#random integer within a given range

In [30]:
np.random.randint(1,6)

4

In [33]:
np.random.randint(1,100,5)

array([15, 15, 37, 72,  7])

In [34]:
#generate random float number

In [36]:
np.random.rand()

0.08596207549369872

In [38]:
np.random.rand(5)

array([0.04701322, 0.76440531, 0.16752969, 0.9300041 , 0.13754975])

In [39]:
#normal distribution random

In [40]:
np.random.randn()

-1.5731540056977993

In [43]:
np.random.randn(10)

array([ 1.82415226,  0.49517833, -1.06828489,  1.18850093,  0.08004093,
        0.98273896, -1.59513491, -0.59641004, -0.21122508, -2.20955616])

arr1

In [44]:
arr1

array([1, 2, 3, 4, 5])

In [45]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [48]:
arr1.ndim

1

In [49]:
arr2.ndim

2

In [50]:
arr3.ndim

3

In [51]:
arr1.shape

(5,)

In [52]:
arr2.shape

(2, 3)

In [53]:
arr3.shape

(2, 2, 2)

In [54]:
arr3.size

8

In [55]:
arr2.size

6

In [56]:
arr1.size

5

In [57]:
arr1.dtype

dtype('int64')

In [58]:
arr2.dtype

dtype('int64')

In [61]:
arr1 = np.array([1,2,3,4,5,6])

In [62]:
arr1

array([1, 2, 3, 4, 5, 6])

In [63]:
arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [64]:
arr1.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
arr1[0]   #indexing always in [] braces

1

In [69]:
 arr1.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [71]:
arr1[1:4]   #slicing

array([2, 3, 4])

In [72]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [73]:
a + b

array([5, 7, 9])

In [74]:
a * b

array([ 4, 10, 18])

In [75]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [76]:
np.sum(arr)

45

In [77]:
np.mean(arr)

5.0

In [78]:
np.std(arr)

2.581988897471611

In [79]:
np.median(arr)

5.0

In [80]:
np.min(arr)

1

In [81]:
np.max(arr)

9

#pandas

Pandas is a powerful Python library for data manipulation and analysis. It provides two primary data structures: Series (1D) and DataFrame (2D), making it easy to work with structured data.

In [82]:
import pandas as pd

In [83]:
data = [10,20,30,40,50,60,70]

In [84]:
data

[10, 20, 30, 40, 50, 60, 70]

In [89]:
series = pd.Series(data, name= "Column_one")

In [90]:
series

0    10
1    20
2    30
3    40
4    50
5    60
6    70
Name: Column_one, dtype: int64

In [91]:
data = [10,20,30]

In [92]:
series = pd.Series(data, name = "count", index = ["A", "B", "C"])

In [93]:
series

A    10
B    20
C    30
Name: count, dtype: int64

In [94]:
fruits = {"Apple":100, "Banana":200, "Cherry":300}

In [99]:
s1 = pd.Series(fruits, name = "Price")

In [100]:
s1

Apple     100
Banana    200
Cherry    300
Name: Price, dtype: int64

@2D data = DataFrame

In [105]:
data = {
    "Roll_No": [101,102,103,104],
    "Name": ["Pranjal", "Riya", "Sakshi", "Astha"],
    "Age": [21,22,23,24]
}

In [106]:
data

{'Roll_No': [101, 102, 103, 104],
 'Name': ['Pranjal', 'Riya', 'Sakshi', 'Astha'],
 'Age': [21, 22, 23, 24]}

In [108]:
type(data)

dict

In [109]:
df =pd.DataFrame(data)

In [110]:
df

Roll_No     Name  Age
0      101  Pranjal   21
1      102     Riya   22
2      103   Sakshi   23
3      104    Astha   24