NumPy (Numerical Python) is a powerful Python library for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

In [4]:
import numpy

ModuleNotFoundError: No module named 'numpy'

In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4,5])

In [4]:
arr1

array([1, 2, 3, 4, 5])

In [5]:
arr2 = np.array([[1,2,3], [4,5,6]])

In [6]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr3 = np.array([
    [[1,2], [3,4]],
    [[5,6],[7,8]]
    ])

In [8]:
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [9]:
#metrix

In [10]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
zero_matrix = list(map(lambda _: [0] * 3, range(3)))

In [12]:
zero_matrix

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]

In [13]:
zero_matrix = []
for _ in range(3):
    zero_matrix.append([0] * 3)

print(zero_matrix)


[[0, 0, 0], [0, 0, 0], [0, 0, 0]]


In [14]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [15]:
np.full((3,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#range

In [17]:
np.arange(1,10,2)   # 1 to 10 is the range, and 2 is stepsize

array([1, 3, 5, 7, 9])

In [18]:
np.arange(1.0,5.0,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [19]:
np.linspace(1,10,7)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [20]:
np.linspace(1,30,20)

array([ 1.        ,  2.52631579,  4.05263158,  5.57894737,  7.10526316,
        8.63157895, 10.15789474, 11.68421053, 13.21052632, 14.73684211,
       16.26315789, 17.78947368, 19.31578947, 20.84210526, 22.36842105,
       23.89473684, 25.42105263, 26.94736842, 28.47368421, 30.        ])

#random

In [21]:
#random integer within a given range

In [22]:
np.random.randint(1,6)

2

In [23]:
np.random.randint(1,100,5)

array([82, 63, 60, 86, 37])

In [24]:
#generate random float number

In [25]:
np.random.rand()

0.33222464288609166

In [26]:
np.random.rand(5)

array([0.14788777, 0.16446847, 0.34976001, 0.80047042, 0.48407172])

In [27]:
#normal distribution random

In [28]:
np.random.randn()

-0.2533354112615452

In [29]:
np.random.randn(10)

array([ 1.43186466,  0.90811262, -0.5566914 ,  1.87678975, -0.07114573,
       -0.13629244, -1.97229774,  0.47351477,  0.97680286,  1.0985312 ])

arr1

In [30]:
arr1

array([1, 2, 3, 4, 5])

In [31]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [33]:
arr1.ndim

1

In [34]:
arr2.ndim

2

In [35]:
arr3.ndim

3

In [36]:
arr1.shape

(5,)

In [37]:
arr2.shape

(2, 3)

In [38]:
arr3.shape

(2, 2, 2)

In [39]:
arr3.size

8

In [40]:
arr2.size

6

In [41]:
arr1.size

5

In [42]:
arr1.dtype

dtype('int64')

In [43]:
arr2.dtype

dtype('int64')

In [44]:
arr1 = np.array([1,2,3,4,5,6])

In [45]:
arr1

array([1, 2, 3, 4, 5, 6])

In [46]:
arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
arr1.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
arr1[0]   #indexing always in [] braces

1

In [49]:
 arr1.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [50]:
arr1[1:4]   #slicing

array([2, 3, 4])

In [51]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [52]:
a + b

array([5, 7, 9])

In [53]:
a * b

array([ 4, 10, 18])

In [54]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [55]:
np.sum(arr)

45

In [56]:
np.mean(arr)

5.0

In [57]:
np.std(arr)

2.581988897471611

In [58]:
np.median(arr)

5.0

In [59]:
np.min(arr)

1

In [60]:
np.max(arr)

9

#pandas

Pandas is a powerful Python library for data manipulation and analysis. It provides two primary data structures: Series (1D) and DataFrame (2D), making it easy to work with structured data.

In [61]:
import pandas as pd

In [62]:
data = [10,20,30,40,50,60,70]

In [63]:
data

[10, 20, 30, 40, 50, 60, 70]

In [64]:
series = pd.Series(data, name= "Column_one")

In [65]:
series

0    10
1    20
2    30
3    40
4    50
5    60
6    70
Name: Column_one, dtype: int64

In [66]:
data = [10,20,30]

In [67]:
series = pd.Series(data, name = "count", index = ["A", "B", "C"])

In [68]:
series

A    10
B    20
C    30
Name: count, dtype: int64

In [69]:
fruits = {"Apple":100, "Banana":200, "Cherry":300}

In [70]:
s1 = pd.Series(fruits, name = "Price")

In [71]:
s1

Apple     100
Banana    200
Cherry    300
Name: Price, dtype: int64

@2D data = DataFrame

In [72]:
data = {
    "Roll_No": [101,102,103,104],
    "Name": ["Pranjal", "Riya", "Sakshi", "Astha"],
    "Age": [21,22,23,24]
}

In [73]:
data

{'Roll_No': [101, 102, 103, 104],
 'Name': ['Pranjal', 'Riya', 'Sakshi', 'Astha'],
 'Age': [21, 22, 23, 24]}

In [74]:
type(data)

dict

In [75]:
df =pd.DataFrame(data)

In [76]:
df

Roll_No     Name  Age
0      101  Pranjal   21
1      102     Riya   22
2      103   Sakshi   23
3      104    Astha   24

In [77]:
data = {
    "Roll_No": 101,
    "Name": "Pranjal",
    "Age": 21
}

In [80]:
type(data)

dict

In [81]:
df = pd.read_csv("/content/sample_data/california_housing_test.csv")

In [82]:
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0   
1       -118.30     34.26                43.0       1510.0           310.0   
2       -117.81     33.78                27.0       3589.0           507.0   
3       -118.36     33.82                28.0         67.0            15.0   
4       -119.67     36.33                19.0       1241.0           244.0   
...         ...       ...                 ...          ...             ...   
2995    -119.86     34.42                23.0       1450.0           642.0   
2996    -118.14     34.06                27.0       5257.0          1082.0   
2997    -119.70     36.30                10.0        956.0           201.0   
2998    -117.12     34.10                40.0         96.0            14.0   
2999    -119.63     34.42                42.0       1765.0           263.0   

      population  households  median_income  median_house_value  
0         1537.0       606.0         6.6085            344700.0  
1          809.0       277.0         3.5990            176500.0  
2         1484.0       495.0         5.7934            270500.0  
3           49.0        11.0         6.1359            330000.0  
4          850.0       237.0         2.9375             81700.0  
...          ...         ...            ...                 ...  
2995      1258.0       607.0         1.1790            225000.0  
2996      3496.0      1036.0         3.3906            237200.0  
2997       693.0       220.0         2.2895             62000.0  
2998        46.0        14.0         3.2708            162500.0  
2999       753.0       260.0         8.5608            500001.0  

[3000 rows x 9 columns]

In [83]:
df.to_csv("dreamwithdata.csv", index= False)

In [85]:
df.info()  #summery of data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB


In [86]:
df.describe()  #statastical summery

longitude    latitude  housing_median_age   total_rooms  \
count  3000.000000  3000.00000         3000.000000   3000.000000   
mean   -119.589200    35.63539           28.845333   2599.578667   
std       1.994936     2.12967           12.555396   2155.593332   
min    -124.180000    32.56000            1.000000      6.000000   
25%    -121.810000    33.93000           18.000000   1401.000000   
50%    -118.485000    34.27000           29.000000   2106.000000   
75%    -118.020000    37.69000           37.000000   3129.000000   
max    -114.490000    41.92000           52.000000  30450.000000   

       total_bedrooms    population  households  median_income  \
count     3000.000000   3000.000000  3000.00000    3000.000000   
mean       529.950667   1402.798667   489.91200       3.807272   
std        415.654368   1030.543012   365.42271       1.854512   
min          2.000000      5.000000     2.00000       0.499900   
25%        291.000000    780.000000   273.00000       2.544000   
50%        437.000000   1155.000000   409.50000       3.487150   
75%        636.000000   1742.750000   597.25000       4.656475   
max       5419.000000  11935.000000  4930.00000      15.000100   

       median_house_value  
count          3000.00000  
mean         205846.27500  
std          113119.68747  
min           22500.00000  
25%          121200.00000  
50%          177650.00000  
75%          263975.00000  
max          500001.00000

In [88]:
df.shape

(3000, 9)

In [89]:
df['longitude']

0      -122.05
1      -118.30
2      -117.81
3      -118.36
4      -119.67
         ...  
2995   -119.86
2996   -118.14
2997   -119.70
2998   -117.12
2999   -119.63
Name: longitude, Length: 3000, dtype: float64

In [90]:
df[['longitude', 'latitude']]

longitude  latitude
0       -122.05     37.37
1       -118.30     34.26
2       -117.81     33.78
3       -118.36     33.82
4       -119.67     36.33
...         ...       ...
2995    -119.86     34.42
2996    -118.14     34.06
2997    -119.70     36.30
2998    -117.12     34.10
2999    -119.63     34.42

[3000 rows x 2 columns]

In [91]:
df.iloc[1]

longitude               -118.300
latitude                  34.260
housing_median_age        43.000
total_rooms             1510.000
total_bedrooms           310.000
population               809.000
households               277.000
median_income              3.599
median_house_value    176500.000
Name: 1, dtype: float64

In [92]:
df.iloc[1:3]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   

   population  households  median_income  median_house_value  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0

In [93]:
s1

Apple     100
Banana    200
Cherry    300
Name: Price, dtype: int64

In [94]:
s1.iloc[1]

200

In [95]:
s1.loc['Cherry']

300

In [96]:
df.describe()

longitude    latitude  housing_median_age   total_rooms  \
count  3000.000000  3000.00000         3000.000000   3000.000000   
mean   -119.589200    35.63539           28.845333   2599.578667   
std       1.994936     2.12967           12.555396   2155.593332   
min    -124.180000    32.56000            1.000000      6.000000   
25%    -121.810000    33.93000           18.000000   1401.000000   
50%    -118.485000    34.27000           29.000000   2106.000000   
75%    -118.020000    37.69000           37.000000   3129.000000   
max    -114.490000    41.92000           52.000000  30450.000000   

       total_bedrooms    population  households  median_income  \
count     3000.000000   3000.000000  3000.00000    3000.000000   
mean       529.950667   1402.798667   489.91200       3.807272   
std        415.654368   1030.543012   365.42271       1.854512   
min          2.000000      5.000000     2.00000       0.499900   
25%        291.000000    780.000000   273.00000       2.544000   
50%        437.000000   1155.000000   409.50000       3.487150   
75%        636.000000   1742.750000   597.25000       4.656475   
max       5419.000000  11935.000000  4930.00000      15.000100   

       median_house_value  
count          3000.00000  
mean         205846.27500  
std          113119.68747  
min           22500.00000  
25%          121200.00000  
50%          177650.00000  
75%          263975.00000  
max          500001.00000

In [97]:
filter_df = df[df['total_rooms'] > 1500]

In [98]:
filter_df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0   
1       -118.30     34.26                43.0       1510.0           310.0   
2       -117.81     33.78                27.0       3589.0           507.0   
7       -120.65     35.48                19.0       2310.0           471.0   
8       -122.84     38.40                15.0       3080.0           617.0   
...         ...       ...                 ...          ...             ...   
2990    -118.23     34.09                49.0       1638.0           456.0   
2991    -117.17     34.28                13.0       4867.0           718.0   
2993    -117.91     33.60                37.0       2088.0           510.0   
2996    -118.14     34.06                27.0       5257.0          1082.0   
2999    -119.63     34.42                42.0       1765.0           263.0   

      population  households  median_income  median_house_value  
0         1537.0       606.0         6.6085            344700.0  
1          809.0       277.0         3.5990            176500.0  
2         1484.0       495.0         5.7934            270500.0  
7         1341.0       441.0         3.2250            166900.0  
8         1446.0       599.0         3.6696            194400.0  
...          ...         ...            ...                 ...  
2990      1500.0       430.0         2.6923            150000.0  
2991       780.0       250.0         7.1997            253800.0  
2993       673.0       390.0         5.1048            500001.0  
2996      3496.0      1036.0         3.3906            237200.0  
2999       753.0       260.0         8.5608            500001.0  

[2118 rows x 9 columns]

In [101]:
filter_df1 = df[df['total_rooms'] < 100]

In [2]:
filter_df1

NameError: name 'filter_df1' is not defined

In [3]:
df.isnull()

NameError: name 'df' is not defined

In [104]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [105]:
df.fillna(value = 10, inplace= True)

In [106]:
df.dropna(inplace= True)

In [107]:
df.rename(columns={"housing_median_age":"housing_age"})

longitude  latitude  housing_age  total_rooms  total_bedrooms  \
0       -122.05     37.37         27.0       3885.0           661.0   
1       -118.30     34.26         43.0       1510.0           310.0   
2       -117.81     33.78         27.0       3589.0           507.0   
3       -118.36     33.82         28.0         67.0            15.0   
4       -119.67     36.33         19.0       1241.0           244.0   
...         ...       ...          ...          ...             ...   
2995    -119.86     34.42         23.0       1450.0           642.0   
2996    -118.14     34.06         27.0       5257.0          1082.0   
2997    -119.70     36.30         10.0        956.0           201.0   
2998    -117.12     34.10         40.0         96.0            14.0   
2999    -119.63     34.42         42.0       1765.0           263.0   

      population  households  median_income  median_house_value  
0         1537.0       606.0         6.6085            344700.0  
1          809.0       277.0         3.5990            176500.0  
2         1484.0       495.0         5.7934            270500.0  
3           49.0        11.0         6.1359            330000.0  
4          850.0       237.0         2.9375             81700.0  
...          ...         ...            ...                 ...  
2995      1258.0       607.0         1.1790            225000.0  
2996      3496.0      1036.0         3.3906            237200.0  
2997       693.0       220.0         2.2895             62000.0  
2998        46.0        14.0         3.2708            162500.0  
2999       753.0       260.0         8.5608            500001.0  

[3000 rows x 9 columns]

In [108]:
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0   
1       -118.30     34.26                43.0       1510.0           310.0   
2       -117.81     33.78                27.0       3589.0           507.0   
3       -118.36     33.82                28.0         67.0            15.0   
4       -119.67     36.33                19.0       1241.0           244.0   
...         ...       ...                 ...          ...             ...   
2995    -119.86     34.42                23.0       1450.0           642.0   
2996    -118.14     34.06                27.0       5257.0          1082.0   
2997    -119.70     36.30                10.0        956.0           201.0   
2998    -117.12     34.10                40.0         96.0            14.0   
2999    -119.63     34.42                42.0       1765.0           263.0   

      population  households  median_income  median_house_value  
0         1537.0       606.0         6.6085            344700.0  
1          809.0       277.0         3.5990            176500.0  
2         1484.0       495.0         5.7934            270500.0  
3           49.0        11.0         6.1359            330000.0  
4          850.0       237.0         2.9375             81700.0  
...          ...         ...            ...                 ...  
2995      1258.0       607.0         1.1790            225000.0  
2996      3496.0      1036.0         3.3906            237200.0  
2997       693.0       220.0         2.2895             62000.0  
2998        46.0        14.0         3.2708            162500.0  
2999       753.0       260.0         8.5608            500001.0  

[3000 rows x 9 columns]

In [109]:
df['housing_median_age'].replace(27, 30)

0       30.0
1       43.0
2       30.0
3       28.0
4       19.0
        ... 
2995    23.0
2996    30.0
2997    10.0
2998    40.0
2999    42.0
Name: housing_median_age, Length: 3000, dtype: float64

In [110]:
df['housing_median_age']= df['housing_median_age'].astype(int)

In [111]:
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                  27       3885.0           661.0   
1       -118.30     34.26                  43       1510.0           310.0   
2       -117.81     33.78                  27       3589.0           507.0   
3       -118.36     33.82                  28         67.0            15.0   
4       -119.67     36.33                  19       1241.0           244.0   
...         ...       ...                 ...          ...             ...   
2995    -119.86     34.42                  23       1450.0           642.0   
2996    -118.14     34.06                  27       5257.0          1082.0   
2997    -119.70     36.30                  10        956.0           201.0   
2998    -117.12     34.10                  40         96.0            14.0   
2999    -119.63     34.42                  42       1765.0           263.0   

      population  households  median_income  median_house_value  
0         1537.0       606.0         6.6085            344700.0  
1          809.0       277.0         3.5990            176500.0  
2         1484.0       495.0         5.7934            270500.0  
3           49.0        11.0         6.1359            330000.0  
4          850.0       237.0         2.9375             81700.0  
...          ...         ...            ...                 ...  
2995      1258.0       607.0         1.1790            225000.0  
2996      3496.0      1036.0         3.3906            237200.0  
2997       693.0       220.0         2.2895             62000.0  
2998        46.0        14.0         3.2708            162500.0  
2999       753.0       260.0         8.5608            500001.0  

[3000 rows x 9 columns]

In [112]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                  27       3885.0           661.0   
1    -118.30     34.26                  43       1510.0           310.0   
2    -117.81     33.78                  27       3589.0           507.0   
3    -118.36     33.82                  28         67.0            15.0   
4    -119.67     36.33                  19       1241.0           244.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0        11.0         6.1359            330000.0  
4       850.0       237.0         2.9375             81700.0

In [113]:
df.head(1)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                  27       3885.0           661.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0

In [114]:
df.tail()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
2995    -119.86     34.42                  23       1450.0           642.0   
2996    -118.14     34.06                  27       5257.0          1082.0   
2997    -119.70     36.30                  10        956.0           201.0   
2998    -117.12     34.10                  40         96.0            14.0   
2999    -119.63     34.42                  42       1765.0           263.0   

      population  households  median_income  median_house_value  
2995      1258.0       607.0         1.1790            225000.0  
2996      3496.0      1036.0         3.3906            237200.0  
2997       693.0       220.0         2.2895             62000.0  
2998        46.0        14.0         3.2708            162500.0  
2999       753.0       260.0         8.5608            500001.0

In [116]:
df.tail(2)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
2998    -117.12     34.10                  40         96.0            14.0   
2999    -119.63     34.42                  42       1765.0           263.0   

      population  households  median_income  median_house_value  
2998        46.0        14.0         3.2708            162500.0  
2999       753.0       260.0         8.5608            500001.0

In [121]:
df['pranjal'] = df['housing_median_age'] / 2

In [122]:
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                  27       3885.0           661.0   
1       -118.30     34.26                  43       1510.0           310.0   
2       -117.81     33.78                  27       3589.0           507.0   
3       -118.36     33.82                  28         67.0            15.0   
4       -119.67     36.33                  19       1241.0           244.0   
...         ...       ...                 ...          ...             ...   
2995    -119.86     34.42                  23       1450.0           642.0   
2996    -118.14     34.06                  27       5257.0          1082.0   
2997    -119.70     36.30                  10        956.0           201.0   
2998    -117.12     34.10                  40         96.0            14.0   
2999    -119.63     34.42                  42       1765.0           263.0   

      population  households  median_income  median_house_value  pranjal  
0         1537.0       606.0         6.6085            344700.0     13.5  
1          809.0       277.0         3.5990            176500.0     21.5  
2         1484.0       495.0         5.7934            270500.0     13.5  
3           49.0        11.0         6.1359            330000.0     14.0  
4          850.0       237.0         2.9375             81700.0      9.5  
...          ...         ...            ...                 ...      ...  
2995      1258.0       607.0         1.1790            225000.0     11.5  
2996      3496.0      1036.0         3.3906            237200.0     13.5  
2997       693.0       220.0         2.2895             62000.0      5.0  
2998        46.0        14.0         3.2708            162500.0     20.0  
2999       753.0       260.0         8.5608            500001.0     21.0  

[3000 rows x 10 columns]